front_cloud_to_scan:
  ros__parameters:
    use_sim_time: False
    frame_id: front_camera_link
    pointcloud_topic: /front_camera/points
    scan_topic: /front_camera/scan
    frequency: 30
    x_max: 10.
    x_min: .6
    y_max: 20.
    y_min: -20.
    z_max: -0.05
    z_min: -0.20
    angle_max: 0.785
    angle_min: -0.785
    rays_number: 120

path_planning:
  ros__parameters:
    frequency: 30
    global_grid_topic: /map
    odom_topic: /odom
    goal_topic: /goal_pose
    path_topic: /path
    robot_collision_radius: 1.5
    goal_radius: 3.
    steering_value: 0.12
    path_discrete: 0.5
    robot_base_frame: map
    grid_resolution: 0.1