front_cloud_to_scan:
  ros__parameters:
    use_sim_time: False
    frame_id: front_camera_link
    pointcloud_topic: /front_camera/points
    scan_topic: /front_camera/scan
    frequency: 30
    x_max: 20.0
    x_min: 0.6
    y_max: 20.0
    y_min: -20.0
    z_max: 0.0
    z_min: -0.25
    angle_max: 0.785
    angle_min: -0.785
    rays_number: 120

mapping:
  ros__parameters:
    frequency: 30
    front_scan_topic: /front_camera/scan
    rear_scan_topic: /rear_camera/scan
    odom_topic: /odom
    map_topic: /map
    robot_base_frame: chassis
    robot_collision_radius: 2.5
    map_size: 150
    map_resolution: 0.1
    map_frame: map
    front_scan_position: [2.2, 0.0, 0.0]
    rear_scan_position: [-2.2, 0.0, 0.0]

path_planning:
  ros__parameters:
    frequency: 30
    global_grid_topic: /map
    odom_topic: /odom
    goal_topic: /goal_pose
    path_topic: /path
    robot_collision_radius: 1.5
    goal_radius: 2.0
    steering_value: 0.24 # не ставить меньше 0.2
    path_discrete: 1.0
    robot_base_frame: map
    grid_resolution: 0.1
    timeout: 2.0

waypoint_following:
  ros__parameters:
    frequency: 30
    odom_topic: /odom
    goal_topic: /goal_pose
    goal_radius: 5.0
#    waypoints: [19.8653, -10.3495, 29.2345, -23.4966, 23.618, -34.74]
#    waypoints: [23.618, -34.74]
    waypoints: [20.6453, -9.80267, 24.3003, -31.9225, 13.7962, -46.5684, -3.74152, -51.6982, -0.0843143, -0.171923]
    map_frame: map
    start_following: False # Начинать следование только после запуска и инициализации всех нод